[workspace]

members = [
    "anoncreds",
    "indy-utils",
]

[profile.release]
lto = true
codegen-units = 1

# We override the dependency on openssl-src with the latest from `git` as this adds a build
# target for `aarch64-apple-ios-sim`. Once this is released, we can depend on the latest from
# crates.io
[patch.crates-io]
openssl-src = { git = "https://github.com/alexcrichton/openssl-src-rs", branch = "release/111" }
