name: "Run Tests"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lints:
    name: Lints

    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Cache cargo resources
        uses: Swatinem/rust-cache@v1

      - name: Cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  test:
    name: Test Suite
    needs: [lints]

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Cache cargo resources
        uses: Swatinem/rust-cache@v1

      - name: Debug build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path anoncreds/Cargo.toml --features vendored

      - name: Test indy-utils
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path indy-utils/Cargo.toml

      - name: Test anoncreds (vendored)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path anoncreds/Cargo.toml --features vendored
